export {default as layer1} from "../assets/music/layer1.mp3"
export {default as layer2} from "../assets/music/layer2.mp3"
export {default as layer3} from "../assets/music/layer3.mp3"
export {default as layer4} from "../assets/music/layer4.mp3"
export {default as layer5}from "../assets/music/layer5.mp3"
export {default as layer6} from "../assets/music/layer6.mp3"
export {default as layer7}from "../assets/music/layer7.mp3"
export {default as recordScratch} from "../assets/music/record-scratch-1.wav"
export {default as scratch}from "../assets/music/scratch.mp3"

